spring:
  application:
    name: nocode-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_nocode
    username: root
    password: 647252
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.nocode.backend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-xxx
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-xxx
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

# Log
logging:
  charset:
    console: UTF-8
    file: UTF-8