spring:
  application:
    name: nocode-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: name
    password: pwd
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.nocode.backend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  application:
    qos-enable: true
    qos-port: 0
  protocol:
    name: tri
    port: 50051
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
